# Generated by Django 2.2.16 on 2022-06-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
