# Generated by Django 2.2.16 on 2022-06-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220623_1357'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='unique_year_title',
        ),
    ]
